// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Account is the predicate function for account builders.
type Account func(*sql.Selector)

// Calendar is the predicate function for calendar builders.
type Calendar func(*sql.Selector)

// Event is the predicate function for event builders.
type Event func(*sql.Selector)

// Secret is the predicate function for secret builders.
type Secret func(*sql.Selector)
