// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	notify "github.com/AvengeMedia/dankcalendar/core/internal/notify"
	mock "github.com/stretchr/testify/mock"
)

// MockSender is an autogenerated mock type for the Sender type
type MockSender struct {
	mock.Mock
}

type MockSender_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSender) EXPECT() *MockSender_Expecter {
	return &MockSender_Expecter{mock: &_m.Mock}
}

// Dismiss provides a mock function with given fields: id
func (_m *MockSender) Dismiss(id uint32) {
	_m.Called(id)
}

// MockSender_Dismiss_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Dismiss'
type MockSender_Dismiss_Call struct {
	*mock.Call
}

// Dismiss is a helper method to define mock.On call
//   - id uint32
func (_e *MockSender_Expecter) Dismiss(id interface{}) *MockSender_Dismiss_Call {
	return &MockSender_Dismiss_Call{Call: _e.mock.On("Dismiss", id)}
}

func (_c *MockSender_Dismiss_Call) Run(run func(id uint32)) *MockSender_Dismiss_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uint32))
	})
	return _c
}

func (_c *MockSender_Dismiss_Call) Return() *MockSender_Dismiss_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockSender_Dismiss_Call) RunAndReturn(run func(uint32)) *MockSender_Dismiss_Call {
	_c.Run(run)
	return _c
}

// Send provides a mock function with given fields: n
func (_m *MockSender) Send(n notify.Notification) (uint32, error) {
	ret := _m.Called(n)

	if len(ret) == 0 {
		panic("no return value specified for Send")
	}

	var r0 uint32
	var r1 error
	if rf, ok := ret.Get(0).(func(notify.Notification) (uint32, error)); ok {
		return rf(n)
	}
	if rf, ok := ret.Get(0).(func(notify.Notification) uint32); ok {
		r0 = rf(n)
	} else {
		r0 = ret.Get(0).(uint32)
	}

	if rf, ok := ret.Get(1).(func(notify.Notification) error); ok {
		r1 = rf(n)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSender_Send_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Send'
type MockSender_Send_Call struct {
	*mock.Call
}

// Send is a helper method to define mock.On call
//   - n notify.Notification
func (_e *MockSender_Expecter) Send(n interface{}) *MockSender_Send_Call {
	return &MockSender_Send_Call{Call: _e.mock.On("Send", n)}
}

func (_c *MockSender_Send_Call) Run(run func(n notify.Notification)) *MockSender_Send_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(notify.Notification))
	})
	return _c
}

func (_c *MockSender_Send_Call) Return(_a0 uint32, _a1 error) *MockSender_Send_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSender_Send_Call) RunAndReturn(run func(notify.Notification) (uint32, error)) *MockSender_Send_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockSender creates a new instance of MockSender. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSender(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSender {
	mock := &MockSender{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
