// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockSecretStore is an autogenerated mock type for the SecretStore type
type MockSecretStore struct {
	mock.Mock
}

type MockSecretStore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSecretStore) EXPECT() *MockSecretStore_Expecter {
	return &MockSecretStore_Expecter{mock: &_m.Mock}
}

// Delete provides a mock function with given fields: ctx, accountID, key
func (_m *MockSecretStore) Delete(ctx context.Context, accountID string, key string) error {
	ret := _m.Called(ctx, accountID, key)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, accountID, key)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockSecretStore_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockSecretStore_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - accountID string
//   - key string
func (_e *MockSecretStore_Expecter) Delete(ctx interface{}, accountID interface{}, key interface{}) *MockSecretStore_Delete_Call {
	return &MockSecretStore_Delete_Call{Call: _e.mock.On("Delete", ctx, accountID, key)}
}

func (_c *MockSecretStore_Delete_Call) Run(run func(ctx context.Context, accountID string, key string)) *MockSecretStore_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockSecretStore_Delete_Call) Return(_a0 error) *MockSecretStore_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockSecretStore_Delete_Call) RunAndReturn(run func(context.Context, string, string) error) *MockSecretStore_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function with given fields: ctx, accountID, key
func (_m *MockSecretStore) Get(ctx context.Context, accountID string, key string) ([]byte, error) {
	ret := _m.Called(ctx, accountID, key)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 []byte
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) ([]byte, error)); ok {
		return rf(ctx, accountID, key)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) []byte); ok {
		r0 = rf(ctx, accountID, key)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, accountID, key)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSecretStore_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockSecretStore_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - accountID string
//   - key string
func (_e *MockSecretStore_Expecter) Get(ctx interface{}, accountID interface{}, key interface{}) *MockSecretStore_Get_Call {
	return &MockSecretStore_Get_Call{Call: _e.mock.On("Get", ctx, accountID, key)}
}

func (_c *MockSecretStore_Get_Call) Run(run func(ctx context.Context, accountID string, key string)) *MockSecretStore_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockSecretStore_Get_Call) Return(_a0 []byte, _a1 error) *MockSecretStore_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSecretStore_Get_Call) RunAndReturn(run func(context.Context, string, string) ([]byte, error)) *MockSecretStore_Get_Call {
	_c.Call.Return(run)
	return _c
}

// Set provides a mock function with given fields: ctx, accountID, key, value
func (_m *MockSecretStore) Set(ctx context.Context, accountID string, key string, value []byte) error {
	ret := _m.Called(ctx, accountID, key, value)

	if len(ret) == 0 {
		panic("no return value specified for Set")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, []byte) error); ok {
		r0 = rf(ctx, accountID, key, value)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockSecretStore_Set_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Set'
type MockSecretStore_Set_Call struct {
	*mock.Call
}

// Set is a helper method to define mock.On call
//   - ctx context.Context
//   - accountID string
//   - key string
//   - value []byte
func (_e *MockSecretStore_Expecter) Set(ctx interface{}, accountID interface{}, key interface{}, value interface{}) *MockSecretStore_Set_Call {
	return &MockSecretStore_Set_Call{Call: _e.mock.On("Set", ctx, accountID, key, value)}
}

func (_c *MockSecretStore_Set_Call) Run(run func(ctx context.Context, accountID string, key string, value []byte)) *MockSecretStore_Set_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].([]byte))
	})
	return _c
}

func (_c *MockSecretStore_Set_Call) Return(_a0 error) *MockSecretStore_Set_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockSecretStore_Set_Call) RunAndReturn(run func(context.Context, string, string, []byte) error) *MockSecretStore_Set_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockSecretStore creates a new instance of MockSecretStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSecretStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSecretStore {
	mock := &MockSecretStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
